version: "3.8"

services:
  idde-mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    container_name: idde-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: HnsAdrt0WtynpKJd
      MYSQL_USER: idde
      MYSQL_PASSWORD: VgJUjBd8
      MYSQL_DATABASE: idde
    volumes:
      - iddemysqlvolume:/var/lib/mysql
    networks:
      - idde

volumes:
  iddemysqlvolume:

networks:
  idde:
