name: Lint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: gradle:8.4.0-jdk21-jammy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set GRADLE_USER_HOME
        run: echo "GRADLE_USER_HOME=$PWD/.gradle" >> $GITHUB_ENV

      - name: Build with Gradle
        run: gradle build --console=plain --no-daemon
